plugin {
    hyprscrolling {
        column_width = 0.7
        fullscreen_on_one_column = true
        focus_fit_method = 0
    }
}

bind = SUPER, period, layoutmsg, move +col
bind = SUPER, comma, layoutmsg, move -col
bind = SUPER SHIFT, period, layoutmsg, movewindowto r
bind = SUPER SHIFT, comma, layoutmsg, movewindowto l
bind = SUPER SHIFT, up, layoutmsg, movewindowto u
bind = SUPER SHIFT, down, layoutmsg, movewindowto d
# bind = SUPER SHIFT, F, layoutmsg, fit active
bind = SUPER SHIFT, G, layoutmsg, togglefit
bind = SUPER ALT, Z, layoutmsg, colresize +0.2
bind = SUPER ALT, X, layoutmsg, colresize -0.2

