plugin {
    hyprexpo {
        columns = 3
        gap_size = 10
        bg_col = rgb(AAAAAA)
        workspace_method = workspace # [center/first] [workspace] e.g. first 1 or center m+1
        skip_empty = false
        gesture_distance = 300 # how far is the "max" for the gesture
    }
}

# This will toggle HyprExpo when SUPER+g is pressed
bind = SUPER, g, hyprexpo:expo, toggle
