
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = match:class xdg-desktop-portal-gtk, opacity 0.80 0.70
windowrule = match:class blueman-manager, opacity 0.80 0.70
windowrule = match:class com.saivert.pwvucontrol, opacity 0.80 0.70
windowrule = match:class nm-applet, opacity 0.80 0.70
windowrule = match:class nm-connection-editor, opacity 0.80 0.70
windowrule = match:class org.kde.polkit-kde-authentication-agent-1, opacity 0.80 0.70

windowrule = match:class com.saivert.pwvucontrol, float on
windowrule = match:class blueman-manager, float on
windowrule = match:class nm-applet, float on
windowrule = match:class nm-connection-editor, float on
windowrule = match:class org.kde.polkit-kde-authentication-agent-1, float on
windowrule = match:class xdg-desktop-portal-gtk, float on
